[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd src/client && npm install"
]

[phases.build]
cmds = [
  "cd src/client && npm run build"
]

[start]
cmd = "npm run start:railway"
