[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
CLIENT_URL = "https://careerconnect-ai-production.up.railway.app"
ENABLE_LOGGING = "true"
LOG_LEVEL = "info"
ENABLE_METRICS = "true"
BCRYPT_ROUNDS = "12"
MAX_FILE_SIZE = "10485760"
UPLOAD_PATH = "./uploads"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
JWT_EXPIRES_IN = "24h"
JWT_REFRESH_EXPIRES_IN = "7d"
