export const typography = {
  fontFamily: '"Source Sans 3", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  fontFamilyDisplay: '"Space Grotesk", "Source Sans 3", sans-serif',
  fontFamilyMono: '"JetBrains Mono", "Courier New", monospace',
  
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemiBold: 600,
  fontWeightBold: 700,
  
  h1: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: 'clamp(1.55rem, 3vw, 2.3rem)',
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: '-0.025em',
  },
  h2: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: 'clamp(1.35rem, 2.4vw, 1.95rem)',
    fontWeight: 700,
    lineHeight: 1.18,
    letterSpacing: '-0.015em',
  },
  h3: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: 'clamp(1.15rem, 1.8vw, 1.55rem)',
    fontWeight: 600,
    lineHeight: 1.22,
    letterSpacing: '-0.01em',
  },
  h4: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: 'clamp(0.98rem, 1.2vw, 1.2rem)',
    fontWeight: 600,
    lineHeight: 1.26,
  },
  h5: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: '1rem',
    fontWeight: 600,
    lineHeight: 1.3,
  },
  h6: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: '0.9rem',
    fontWeight: 600,
    lineHeight: 1.33,
    letterSpacing: '0.005em',
  },
  body1: {
    fontSize: '0.9rem',
    fontWeight: 400,
    lineHeight: 1.6,
    letterSpacing: '0.002em',
  },
  body2: {
    fontSize: '0.875rem',
    fontWeight: 400,
    lineHeight: 1.55,
  },
  subtitle1: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: '0.9rem',
    fontWeight: 500,
    lineHeight: 1.48,
    letterSpacing: '-0.002em',
  },
  subtitle2: {
    fontFamily: '"Source Sans 3", sans-serif',
    fontSize: '0.8125rem',
    fontWeight: 500,
    lineHeight: 1.5,
    letterSpacing: '0.005em',
  },
  button: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: '0.84rem',
    fontWeight: 600,
    lineHeight: 1.35,
    letterSpacing: '0.012em',
    textTransform: 'none',
  },
  caption: {
    fontSize: '0.82rem',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  overline: {
    fontFamily: '"Space Grotesk", sans-serif',
    fontSize: '0.72rem',
    fontWeight: 600,
    lineHeight: 1.3,
    textTransform: 'uppercase',
    letterSpacing: '0.11em',
  },
};
